<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['pagination']['full_tag_open']='<div class="row"><div class="col-xs-12"><div class="dataTables_paginate paging_bootstrap"><ul class="pagination pull-right">';
$config['pagination']['full_tag_close']='</ul></div></div></div>';
$config['pagination']['first_link']='← Trang đầu';
$config['pagination']['first_tag_open']='<li class="prev">';
$config['pagination']['first_tag_close']='</li>';
$config['pagination']['last_link']='Trang cuối';
$config['pagination']['last_tag_open']='<li>';
$config['pagination']['last_tag_close']='</li>';
$config['pagination']['next_link']='Trang sau → ';
$config['pagination']['next_tag_open']='<li class="next">';
$config['pagination']['next_tag_close']='</li>';
$config['pagination']['prev_link']='← Trang trước';
$config['pagination']['prev_tag_open']='<li class="prev">';
$config['pagination']['pre_tag_close']='</li>';
$config['pagination']['cur_tag_open']='<li class="active"><a>';
$config['pagination']['cur_tag_close']='</a></li>';
$config['pagination']['num_tag_open']='<li>';
$config['pagination']['num_tag_close']='</li>';
$config['pagination']['use_page_numbers'] = TRUE;
$config['pagination']['per_page'] = 5;
$config['pagination']['num_link']=7;
$config['pagination']['uri_segment']=4;
$config['pagination']['page_query_string'] = TRUE;
$config['pagination']['query_string_segment'] = 'page';
