/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50156
Source Host           : localhost:3306
Source Database       : utt

Target Server Type    : MYSQL
Target Server Version : 50156
File Encoding         : 65001

Date: 2015-09-27 23:10:06
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `utt_site`
-- ----------------------------
DROP TABLE IF EXISTS `utt_site`;
CREATE TABLE `utt_site` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `template_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `url_name` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `banner` varchar(255) DEFAULT NULL,
  `footer_info` text,
  `desc` varchar(500) DEFAULT NULL,
  `keyword` varchar(300) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `department_id` int(11) NOT NULL,
  `name_header_vn` text NOT NULL,
  `name_header_en` text NOT NULL,
  `position_display` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of utt_site
-- ----------------------------
INSERT INTO `utt_site` VALUES ('1', '1', 'utt', 'utt', null, null, '', 'đại học công nghệ gtvt', '', 'Đại Học Công Nghệ Giao Thông Vận Tải', '0', '', '', '{\"content_01\":{\"cate_id_vn\":\"1\",\"cate_id_en\":\"34\",\"limit\":5},\"content_02\":{\"cate_id_vn\":\"2\",\"cate_id_en\":\"35\",\"limit\":5},\"content_03\":{\"cate_id_vn\":\"3\",\"cate_id_en\":\"36\",\"limit\":5},\"content_04\":{\"cate_id_vn\":\"4\",\"cate_id_en\":\"37\",\"limit\":5},\"content_05\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"38\",\"limit\":5},\"content_06\":{\"cate_id_vn\":\"6\",\"cate_id_en\":\"39\",\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('2', '1', 'qldt', 'qldt', '1441329980logo.png', '1441329980logo.png', 'Địa chỉ: Phòng 206, 207 – Nhà H1 - Trường Đại học Công nghệ GTVT- Số 54 Triều Khúc - Thanh Xuân- Hà Nội Điện thoại: 04.35526713; 04.38547536 Email: phongdaotao@utt.edu.vn.', 'Phòng Đào tạo ', '', 'Phòng Đào tạo ', '4', 'PHÒNG ĐÀO TẠO', 'DEPARTMENT OF TRAINING', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('3', '1', 'sinhvien', 'ct-hssv', '1441333575logo.png', '1441333575logo.png', 'Địa chỉ: Phòng 107, 111, Nhà H1- Trường Đại học Công nghệ GTVT- Số 54 Triều Khúc - Thanh Xuân- Hà Nội  Điện thoại:  Email: phongcthssv@utt.edu.vn', '', '', 'Phòng công tác Học sinh - Sinh viên ', '12', 'PHÒNG CÔNG TÁC HSSV ', 'STUDENT WORK ROOM', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('16', '1', 'cntt', 'cntt', '1441777604logo.png', '1441329836logo.png', 'Địa chỉ : Phòng 403 - Nhà H1 - Trường Đại học Công nghệ GTVT, số 54 Triều Khúc - Thanh Xuân - Hà Nội. - Điện thoại : 043.552.4990 - Email : khoacntt@utt.edu.vn', 'Khoa công nghệ thông tin - Trường Đại học công nghệ Giao thông vận tải ', '', 'Khoa Công nghệ thông tin', '1', '', '', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('17', '1', null, 'qldt-sdh', '1441333413logo.png', '1441333413logo.png', 'Địa chỉ: Phòng 303 Nhà H3 - Trường Đại học Công nghệ GTVT- Số 54 Triều Khúc- Thanh Xuân- Hà Nội. Điện thoại: 043.2222.865 Email: phongdtsdh@utt.edu.vn', '', '', 'Phòng quản lý đào tạo Sau Đại học ', '5', 'PHÒNG ĐÀO TẠO SAU ĐẠI HỌC ', 'ROOM  POSTGRADUTE EDUCATION', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('18', '1', null, 'ktvt', '1441333810logo.png', '1441333810logo.png', 'Địa chỉ tại cơ sở đào tạo Hà Nội: Phòng 508 Nhà H1 - Trường Đại học Công nghệ GTVT, số 54 Triều Khúc- Thanh Xuân- Hà Nội Điện thoại: (04) 35520750; Email:  Địa chỉ tại cơ sở đào tạo Vĩnh Yên: Phòng 205 - Khu hiệu bộ - cơ sở đào tạo Vĩnh Yên, số 278 đường Lam Sơn- Phường Đồng Tâm- TP Vĩnh Yên- Vĩnh Phúc; Điện thoại: (0211) 3843020; Email:    Khoa Kinh tế vận tải được Hiệu trưởng trường Đại học Công nghệ GTVT ra quyết định thành lập số 1453/QĐ-ĐHCNGTVT ngày 23/8/2011', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Khoa Kinh tế Vận tải ', '16', 'KHOA KINH TẾ VẬN TẢI ', 'ECONOMICS DEPARTMENT OF TRANSPORT', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('19', '1', null, 'cong-trinh', '1441333815logo.png', '1441333815logo.png', '', '', '', 'Khoa Công trình ', '2', 'KHOA CÔNG TRÌNH', 'SCIENCE WORKS', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('20', '1', null, 'gdtc', '1441333988logo.png', '1441333988logo.png', '', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Bộ môn Giáo dục thể chất ', '23', 'BỘ MÔN GIÁO DỤC THỂ CHẤT ', 'PHYSICAL EDUCATION CURRICULUM', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('21', '1', null, 'gdqp-an', '1441334042logo.png', '1441334042logo.png', '', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Bộ môn GDQP-AN', '24', 'BỘ MÔN GIÁO DỤC QUỐC PHÒNG AN NINH', 'EDUCATION DEPARTMENT OF DEFENSE SECURITY', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('22', '1', null, 'ck-cngt', '1441334120logo.png', '1441334120logo.png', '', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Khoa Cơ khí ', '3', 'KHOA CƠ KHÍ ', 'ENGINEERING FACULTY', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('23', '1', null, 'vinhyenutteduvn', '14414146461441333413logo.png', '14414146461441333815logo.png', ' Thông tin liên hệ  CƠ SỞ ĐÀO TẠO VĨNH YÊN ĐẠI HỌC CÔNG NGHỆ GIAO THÔNG VẬN TẢI  Đia chỉ : Số 278 Đường Lam Sơn, Phường Đồng Tâm, Thành Phố Vĩnh Yên, tỉnh Vĩnh Phúc  Điện thoại : 0211.3867405 - Fax : 0211 386 7391  Email : infovy@utt.edu.vn', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Cơ sở Đào tạo Vĩnh Yên', '25', 'CƠ SỞ ĐÀO TẠO VĨNH YÊN', 'Training Facility Vinh Yen', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('24', '1', null, 'thainguyenutteduvn', '14414147571441333815logo.png', '14414147571441333413logo.png', '  Cơ sở đào tạo Thái Nguyên Địa chỉ: Phú Thái, Tân Thịnh, TP.Thái Nguyên, Thái Nguyên. Điện thoại: 0280.385.6545 - Fax : 0280.374.6975 Email: infotn@utt.edu.vn - Website: thainguyen.utt.edu.vn', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Cơ sở đào tạo Thái Nguyên', '26', 'CƠ SỞ DÀO TẠO THÁI NGUYÊN', 'Training Facility Thai Nguyen', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('25', '1', null, 'dbcldt', '1441768576defaut_thumbnail_utt19.jpg', '1441768576defaut_thumbnail_utt19.jpg', '', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Phòng Đảm bảo chất lượng Đào tạo', '11', 'Phòng Đảm bảo chất lượng Đào tạo', ' Room Quality Assurance Training', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('26', '1', null, 'bgh-utt', '1441768626defaut_thumbnail_utt19.jpg', '1441768626defaut_thumbnail_utt19.jpg', '', '', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'Ban Giám hiệu', '27', 'Ban Giám hiệu', 'The Board of Presidents', '{\"content_01\":{\"cate_id_vn\":1,\"cate_id_en\":34,\"limit\":5},\"content_02\":{\"cate_id_vn\":2,\"cate_id_en\":35,\"limit\":5},\"content_03\":{\"cate_id_vn\":3,\"cate_id_en\":36,\"limit\":5},\"content_04\":{\"cate_id_vn\":4,\"cate_id_en\":37,\"limit\":5},\"content_05\":{\"cate_id_vn\":5,\"cate_id_en\":38,\"limit\":5},\"content_06\":{\"cate_id_vn\":6,\"cate_id_en\":39,\"limit\":5}}');
INSERT INTO `utt_site` VALUES ('27', '1', null, 'test', null, null, 'dsadasd', 'dsadasd', 'đại học công nghệ gtvt, tuyển sinh đại học, đhcngtvt, đh công nghệ gtvt, tuyển sinh 2015, tuyển sinh liên thông, tư vấn tuyển sinh, đh công nghệ gtvt', 'dsdasd', '20', 'dasdad', 'asdasd', '{\"content_01\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5},\"content_02\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5},\"content_03\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5},\"content_04\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5},\"content_05\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5},\"content_06\":{\"cate_id_vn\":\"5\",\"cate_id_en\":\"34\",\"limit\":5}}');
